workflows:
  ios_sim_unsigned:
    name: iOS Simulator Unsigned (.app)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install JS dependencies
        script: npm ci

      - name: Install CocoaPods (verbose)
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Verify iOS outputs
        script: |
          ls -la ios
          echo "Workspaces:"
          ls -la ios/*.xcworkspace || true
          echo "Projects:"
          ls -la ios/*.xcodeproj || true

      - name: Build Simulator (workspace if present, else project)
        script: |
          set -e
          if [ -d "ios/AlarmLock.xcworkspace" ]; then
            echo "Using workspace"
            xcodebuild \
              -workspace "ios/AlarmLock.xcworkspace" \
              -scheme "AlarmLock" \
              -configuration Debug \
              -sdk iphonesimulator \
              -derivedDataPath build/ios-sim \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY=""
          else
            echo "Workspace missing, using xcodeproj"
            xcodebuild \
              -project "ios/AlarmLock.xcodeproj" \
              -scheme "AlarmLock" \
              -configuration Debug \
              -sdk iphonesimulator \
              -derivedDataPath build/ios-sim \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY=""
          fi

      - name: Zip .app
        script: |
          cd build/ios-sim/Build/Products/Debug-iphonesimulator
          zip -r ../../../../AlarmLock-sim.app.zip AlarmLock.app

    artifacts:
      - build/AlarmLock-sim.app.zip
      - /tmp/xcodebuild_logs/*.log
