workflows:
  ios_sim_unsigned:
    name: iOS Simulator Unsigned (.app)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install JS dependencies
        script: npm ci

      - name: Install CocoaPods (clean + verbose)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          pod install --repo-update --verbose
          cd ..

      - name: Verify Pods + Workspace exist
        script: |
          set -e
          echo "=== ios folder ==="
          ls -la ios
          echo "=== workspaces ==="
          ls -la ios/*.xcworkspace
          echo "=== pods support files ==="
          ls -la "ios/Pods/Target Support Files/Pods-AlarmLock"

      - name: Build Simulator app (unsigned)
        script: |
          set -e
          xcodebuild \
            -workspace "ios/AlarmLock.xcworkspace" \
            -scheme "AlarmLock" \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build/ios-sim \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Zip .app
        script: |
          set -e
          cd build/ios-sim/Build/Products/Debug-iphonesimulator
          zip -r ../../../../AlarmLock-sim.app.zip AlarmLock.app

    artifacts:
      - build/AlarmLock-sim.app.zip
      - /tmp/xcodebuild_logs/*.log
